query DcListHealth($limit: Int) @auth(level: PUBLIC) {
  dcHealths(limit: $limit) {
    id
    label
  }
}

query ListGameRooms($limit: Int) @auth(level: PUBLIC) {
  gameRooms(limit: $limit, orderBy: [{ createdAt: DESC }]) {
    id
    cricApiMatchId
    label
    createdAt
  }
}

query ListGamePlayers($roomId: String!, $limit: Int) @auth(level: PUBLIC) {
  gamePlayers(
    where: { roomId: { eq: $roomId } }
    limit: $limit
    orderBy: [{ createdAt: ASC }]
  ) {
    id
    displayName
    ocrPoints
    createdAt
  }
}

query ListLeagues($limit: Int) @auth(level: PUBLIC) {
  leagues(limit: $limit, orderBy: [{ createdAt: DESC }]) {
    id
    name
    joinCode
    createdAt
  }
}

query ListMatches($leagueId: String!, $limit: Int) @auth(level: PUBLIC) {
  matches(
    where: { leagueId: { eq: $leagueId } }
    limit: $limit
    orderBy: [{ createdAt: DESC }]
  ) {
    id
    label
    matchDate
    cricApiMatchId
    createdAt
  }
}
